### ISSUE TITLE
Community Onboarding Documentation by April 20

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/geocodes_documentation#18]
Create a document that can be used for onboarding communities.

Let's start with an outline of what we think needs to be incorporated, then fill is out.

https://docs.google.com/document/d/1SSeh6deu5WYhTo526ZeSyZ4Mg_XpJyrvgLG7phO9YFU/edit

We have a meeting with Deep Oceans on April 20th. So let's have a draft by then

**Comment by MBcode** [comment]
Is Deep Oceans the same as OIH that has https://book.oceaninfohub.org/ ?

**Comment by MBcode** [comment]
Have a starting page at: https://github.com/earthcube/ec/blob/master/doc/onboarding.md

**Comment by valentinedwv** [comment]
Not everything isa heading. Some [Markdown guidance](https://www.markdownguide.org/basic-syntax/)

```
### Do you have a ROR or re3data or other organizational ID?
#### yes: please supply and we will parse it, then just ask for the fields it did not contain
#### no: please create one: with one or both of these:
* re3data.org/[suggest](https://www.re3data.org/suggest)
* ror.org/[request](https://docs.google.com/forms/d/e/1FAIpQLSdJYaMTCwS7muuTa-B_CnAtCSkKzt19lkirAKG4u7umH9Nosg/viewform)
##### as this ID can be reused much more easily than all the text
```
Renders as:
### Do you have a ROR or re3data or other organizational ID?
#### yes: please supply and we will parse it, then just ask for the fields it did not contain
#### no: please create one: with one or both of these:
* re3data.org/[suggest](https://www.re3data.org/suggest)
* ror.org/[request](https://docs.google.com/forms/d/e/1FAIpQLSdJYaMTCwS7muuTa-B_CnAtCSkKzt19lkirAKG4u7umH9Nosg/viewform)
##### as this ID can be reused much more easily than all the text

----
to:

```
### Do you have a ROR or re3data or other organizational ID?
Identifiers look like, and are utilized for:  (NOTE: add link to actual earthcube identifier)

re3: `re3data.org/suggest`

ror  `ror.org/request`
  
  
* yes: please supply and we will parse it, then just ask for the fields it did not contain
    * enter here ________________
* no: please create one: with one or both of these:  
   * Please create an ID at:
       * re3data.org/[suggest](https://www.re3data.org/suggest)
       * ror.org/[request](https://docs.google.com/forms/d/e/1FAIpQLSdJYaMTCwS7muuTa-B_CnAtCSkKzt19lkirAKG4u7umH9Nosg/viewform)

```

Renders as:

### Do you have a ROR or re3data or other organizational ID?
Identifiers look like, and are utilized for:  (NOTE: add link to actual earthcube identifier)

re3: `re3data.org/suggest`
ror  `ror.org/request`
  
* yes: please supply and we will parse it, then just ask for the fields it did not contain
    * enter here ________________
* no: please create one: with one or both of these:  
   * Please create an ID at:
       * re3data.org/[suggest](https://www.re3data.org/suggest)
       * ror.org/[request](https://docs.google.com/forms/d/e/1FAIpQLSdJYaMTCwS7muuTa-B_CnAtCSkKzt19lkirAKG4u7umH9Nosg/viewform)

**Comment by MBcode** [comment]
ok, do you want it as a template that they fill out within the doc?

**Comment by lmarini** [comment]
Will be community specific. Need to talk to each community.
