### ISSUE TITLE
update docs https://earthcube.github.io/ landing page, where geocodes is running

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/geocodes_documentation#23]
This needs to point at the 
https://earthcube.github.io/geocodes_documentation/
earhtcube.org

Geocodes stack information in the geocodes docs needs to be update

**Comment by ylyangtw** [comment]
Updated it in this [commit](https://github.com/earthcube/geocodes_documentation/commit/34d349e4b3bc6dc12928841473e3b8d0d7f8f250)

**Comment by ylyangtw** [comment]
https://github.com/earthcube/earthcube.github.io

**Comment by ylyangtw** [comment]
Done. Added a page `index.html` to redirect to geocodes_documentation at the root of the [repository](https://github.com/earthcube/earthcube.github.io).
