### ISSUE TITLE
Data load validation for data loading

### ISSUE THREAD

**Issue by valentinedwv** [earthcube/geocodes_documentation#3]
- What do we need to validate a data load
- (Gleaner/nabu) logs, and scripts to look for errors
- Notebook to Validate Dataloading for ECO Staff
  - Duplicate checking
  - Loaded counts
  -

**Comment by MBcode** [comment]
- Would like a demo of latest way to look at logs, by next gleaner mtg
- We do get a list of uniq graphs, but not a count of triples in case that blank-nodes somehow got in their twice
- When nabu does an partial update, we more focus on everything that was set in sitemaps getting into the graph, but still get a listing counts&list-diff that could help w/old things hanging around as well
